
# SEO settings
title: "3code"
title2: "5me" # default: ""
description: "The website for 3code5me."
keywords: "3code5me, games, video games, mods, minecraft, minecraft mods, forge, minecraft forge, forge 1.10, minecraft 1.10, deepcraft"
url: http://3code5me.github.io/ # site url
#baseurl: "/" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/3code5me
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jack Harding, James A. Eschrich"
  thumb    : /images/author.jpg
  email    : 3code5me.business@gmail.com
  url      : http://3code5me.github.io
  github   : http://github.com/3code5me

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
